serverName: "Hub-01"
serverGroup:
  - 'GLOBAL'
  - 'HUBS'

mongo:
  host: "localhost"
  port: 27017
  database: "mCore"
  auth:
    enabled: false
    username: ""
    password: ""
    database: ""

whitelist:
  enabled: false
  enforce: "PLAYER" # PLAYER & RANK
  rank: ""
  players:
    - 'LBuddyBoy'
    - 'SeekDev'

chat:
  slowed:
    enabled: false
    secondsDelay: 3
    duration: -1
    mutedAt: 0
  muted:
    enabled: false
    duration: -1
    mutedAt: 0